In [3]:
from docx import Document
import numpy as np
import pandas as pd 
import json
import re
import os

## NEW TEST DATA

In [4]:
df = pd.read_csv('Binary_Test_File.csv')

In [5]:
df.drop(columns=['File Name'],inplace=True)
df

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time
0,4361,departure,active,lhe,opla,2024-05-14t00:20:00.000,dxb,omdb,2024-05-14t00:20:00.000
1,1876,departure,active,lhe,opla,2024-05-07t04:15:00.000,ruh,oerk,2024-05-07t04:15:00.000
2,6030,departure,active,lhe,opla,2024-05-09t03:10:00.000,doh,othh,2024-05-09t03:10:00.000
3,739,departure,active,lhe,opla,2024-05-12t02:50:00.000,jed,oejn,2024-05-12t02:50:00.000
4,3932,departure,active,lhe,opla,2024-05-16t04:35:00.000,auh,omaa,2024-05-16t04:35:00.000
...,...,...,...,...,...,...,...,...,...
12909,615,departure,active,isb,opis,2024-06-23t09:30:00.000,doh,othh,2024-06-23t09:30:00.000
12910,725,departure,active,isb,opis,2024-06-25t09:50:00.000,ruh,oerk,2024-06-25t10:45:00.000
12911,211,departure,active,isb,opis,2024-06-22t15:35:00.000,dxb,omdb,2024-06-22t15:58:00.000
12912,207,departure,active,isb,opis,2024-06-19t17:00:00.000,khi,opkc,2024-06-19t18:00:00.000
12913,763,departure,active,isb,opis,2024-06-25t00:35:00.000,jed,oejn,2024-06-25t00:35:00.000

In [6]:
columns = ['Scheduled Time','Arrival Estimated Time']
for col in columns:
    df[col] = pd.to_datetime(df[col], format='%Y-%m-%dT%H:%M:%S.%f', errors='coerce')

In [7]:
df['Days'] = df['Scheduled Time'].dt.day
df['Month'] = df['Scheduled Time'].dt.strftime('%b')
df['Year'] = df['Scheduled Time'].dt.year.astype(str)
df['Hour'] = df['Scheduled Time'].dt.hour
df

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,Days,Month,Year,Hour
0,4361,departure,active,lhe,opla,2024-05-14 00:20:00,dxb,omdb,2024-05-14 00:20:00,14,May,2024,0
1,1876,departure,active,lhe,opla,2024-05-07 04:15:00,ruh,oerk,2024-05-07 04:15:00,7,May,2024,4
2,6030,departure,active,lhe,opla,2024-05-09 03:10:00,doh,othh,2024-05-09 03:10:00,9,May,2024,3
3,739,departure,active,lhe,opla,2024-05-12 02:50:00,jed,oejn,2024-05-12 02:50:00,12,May,2024,2
4,3932,departure,active,lhe,opla,2024-05-16 04:35:00,auh,omaa,2024-05-16 04:35:00,16,May,2024,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12909,615,departure,active,isb,opis,2024-06-23 09:30:00,doh,othh,2024-06-23 09:30:00,23,Jun,2024,9
12910,725,departure,active,isb,opis,2024-06-25 09:50:00,ruh,oerk,2024-06-25 10:45:00,25,Jun,2024,9
12911,211,departure,active,isb,opis,2024-06-22 15:35:00,dxb,omdb,2024-06-22 15:58:00,22,Jun,2024,15
12912,207,departure,active,isb,opis,2024-06-19 17:00:00,khi,opkc,2024-06-19 18:00:00,19,Jun,2024,17
12913,763,departure,active,isb,opis,2024-06-25 00:35:00,jed,oejn,2024-06-25 00:35:00,25,Jun,2024,0

In [8]:
df.to_csv('Test.csv',index=False)

In [9]:
df.isnull().sum()

Flight Number             0
Type                      0
Status                    0
Departure IATA Code       0
Departure ICAO Code       0
Scheduled Time            0
Arrival IATA Code         0
Arrival ICAO Code         0
Arrival Estimated Time    0
Days                      0
Month                     0
Year                      0
Hour                      0
dtype: int64